---
# install fits
- name: install zip utility
  become: yes
  package: name=unzip state=present

- name: download fits zip version {{ fits_version }}
  become: yes
  get_url: url=http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_version }}.zip owner={{ capistrano_user }} group={{ capistrano_group }} dest={{ install_path }}/fits-{{ fits_version }}.zip

- name: unpack fits
  become: yes
  unarchive: src={{ install_path }}/fits-{{ fits_version }}.zip dest={{ install_path }}/ creates={{ install_path }}/fits-{{ fits_version }}/fits.sh copy=no

- name: make fits executable
  become: yes
  file: path={{ install_path }}/fits-{{ fits_version }}/fits.sh mode=0755

- name: copy fits scripts
  become: yes
  shell: cp -r {{ install_path }}/fits-{{ fits_version }} /usr/local/lib/ creates=/usr/local/lib/fits-{{ fits_version }}

- name: symlink fits alias
  become: yes
  file: src=/usr/local/lib/fits-{{ fits_version }}/fits.sh dest=/usr/local/bin/fits state=link
  
- name: symlink fits.sh alias
  become: yes
  file: src=/usr/local/lib/fits-{{ fits_version }}/fits.sh dest=/usr/local/bin/fits.sh state=link

- name: set FITS_HOME in fits-env.sh
  become: yes
  lineinfile: dest=/usr/local/lib/fits-{{ fits_version }}/fits-env.sh regexp=^FITS_HOME line=FITS_HOME="/usr/local/lib/fits-{{ fits_version }}" state=present

- name: symlink fits-env.sh alias
  become: yes
  file: src=/usr/local/lib/fits-{{ fits_version }}/fits-env.sh dest=/usr/local/bin/fits-env.sh state=link
