---
# installs postgresql and supporting libraries
- name: install postgresql packages
  package: name={{ item }} state=present
  become: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  notify:
  - set postgres password
  - determine postgres directory
  - configure md5 security
  - restart postgres server
  - create pg hydra database
  - add pg hydra user

- name: create db_backups directory
  become: yes
  file: owner=postgres group=postgres state=directory path=/opt/pg_backups

- name: add pg_backups script
  become: yes
  template: src=pg_backups.j2 dest=/opt/pg_backups/pg_daily_double owner=root group=root mode=0755

- name: add pg_backups cron job
  become: yes
  cron: name="backup pg db" user=postgres job="/opt/pg_backups/pg_daily_double" minute="0" hour="1" state=present

- meta: flush_handlers
