---
# roles/webserver/install/defaults/main.yml
passenger_ver: '5.0.10'
ruby_ver: '2.3.1'
puma_port: '3030'
project_name: sufia-project
app_root: /opt/{{ project_name }}/current
shared_root: /opt/{{ project_name }}/shared
server_name: 127.0.0.1
capistrano_user: deploy
capistrano_group: deploy
webserver: passenger
passenger_root: /etc/apache2/conf-available
# use /etc/httpd/conf.d for CentOS 7
apache: apache2
# use httpd for CentOS 7