---
- iptables_raw:
    name: allow_tcp_solr
    rules: |
      -A INPUT -m state --state NEW -p tcp --destination-port 8983 -j ACCEPT
      -A INPUT -m state --state NEW -p tcp --destination-port 2181 -j ACCEPT
      -A INPUT -m state --state NEW -p tcp --destination-port 2888 -j ACCEPT
      -A INPUT -m state --state NEW -p tcp --destination-port 3888 -j ACCEPT
    weight: 5

- name: "create the directory"
  file:
    path: /opt/solr/server/solr/configsets/samvera
    state: directory
    mode: 0755
    owner: solr
    group: solr

- name: "copy config files ot server"
  copy:
    src: ../solr/config
    dest: /opt/solr/server/solr/configsets/samvera/conf
    owner: solr
    group: solr
    mode: 0644

- name: "check for collection"
  stat:
    path: "/var/solr/data/{{ solr_core }}"
    register: solr_result

- name: "create the collection if it does not exists"
  become: yes
  become_user: solr
  shell: /opt/solr/bin/solr create -c {{ solr_core }} -force -d samvera  creates=/var/solr/data/{{ solr_core }}
  when: solr_result.stat.exists == False
