# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  include ActiveModel::Validations
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata
  include CommonMetadata

  include NestedAttributes

  validates :finding_aid, url: true, allow_blank:true
  validates :exhibit, url: true, allow_blank:true

  def self.indexer
    ::CollectionIndexer
  end

  def suppressed?
    false
  end
end
