# Generated by hyrax:models:install
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include ActiveModel::Validations
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  include CommonMetadata

  include NestedAttributes

  validates :language, url: {message: 'Invalid label for language field!'}, allow_blank:true

  def self.indexer
    ::CollectionIndexer
  end

  def suppressed?
    false
  end
end
