# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  property :rights_override, predicate: ::RDF::URI.new("http://pcdm.org/2015/06/03/rights#rightsOverride"), multiple: false do |index|
    index.as :stored_searchable
  end

  def visibility
    return VisibilityService.visibility_value(self.rights_override) if !self.rights_override.blank?
    super
  end

  def visibility=(value)
    case value
    when VisibilityService::VISIBILITY_TEXT_VALUE_SUPPRESS_DISCOVERY, VisibilityService::VISIBILITY_TEXT_VALUE_CULTURALLY_SENSITIVE
      self.rights_override = VisibilityService.rights_override_value(value)
      value = Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC
    when VisibilityService::VISIBILITY_TEXT_VALUE_METADATA_ONLY
      self.rights_override = VisibilityService.rights_override_value(value)
      value = Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE
    else
      self.rights_override = nil
    end
    super
  end
end

