- name: Get timestamp for repoo
  hosts: localhost
  tasks:
    - shell: 'date +%Y%m%d%H%M%S.%5N'
      register: current_run_timestamp
    - set_fact: ansistrano_release_version = "{{ current_run_timestamp.stdout }}"

- name: Permissions and folders
  hosts: "horton_samvera:horton_sidekiq:horton_sidekiq_master"
  tasks:
    - name: make shared directories
      become: yes
      file:
        path: "{{ item }}" 
        recurse: true
        state: directory
        owner: "{{ capistrano_user }}"
        mode: 0755
      with_items:
        - "{{ ansistrano_deploy_to }}/releases" 
        - "{{ ansistrano_deploy_to }}/shared"
        - "{{ ansistrano_deploy_to }}"

- name: Deploy Rails App
  hosts: "horton_samvera:horton_sidekiq:horton_sidekiq_master"
  become_user: "{{ capistrano_user }}"
  become: yes
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }


- name: Restart Sidekiq
  hosts: "horton_sidekiq:horton_sidekiq_master"
  tasks:
    - name: kick sidekiq
      service: name=sidekiq state=restarted enabled=yes
      become: yes
