- name: Rollback Rails App
  hosts: "damspas-rd_samvera:damspas-rd_sidekiq:damspas-rd_sidekiqmaster"
  become_user: "{{ capistrano_user }}"
  become: yes
  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }
