# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  #config.vm.box = "ubuntu/precise64"

  config.vm.provision :ansible do |ansible|
     ansible.playbook = "playbook.yml"
     ansible.groups = {
        "horton" => ["default"]
     }
     ansible.extra_vars = {
        do_update: true
     }
  end
end
