---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/main.yml
#
# installs solr and fedora in production mode as servlets under tomcat
#
- name: tomcat
  include: tomcat.yml

- name: fedora
  include: fedora.yml
